graph_data_file: 'ebiose_clgp/data/data.jsonl'
gsm8k_validation_file: 'ebiose_clgp/data/gsm8k-validation.pkl'
prompt_tokenizer: 'ebiose_clgp/data_utils/prompt_tokenizer_1.json'
graph_feature_tokenizer: 'ebiose_clgp/data_utils/graph_tokenizer_1.json'
prompt_context_length: 1000
node_feature_context_length: 1000
num_workers: 4