per_gpu_train_batch_size: 32
per_gpu_eval_batch_size: 32
logging_steps: 1

gradient_accumulation_steps: 8
num_train_epochs: 1
train_batch_size: 32
model_save_name: 'CLGP_V1.pth'
saved_checkpoints: 'Model checkpoints'
save_steps: 100

optimizer:
  lr: 0.00001
  eps: 0.00000001
  weight_decay: 0.1