per_gpu_train_batch_size: 16
logging_steps: 10
gradient_accumulation_steps: 2
num_train_epochs: 10
train_batch_size: 16
model_save_name: 'CLGP_V1.pth'
saved_checkpoints: 'Model checkpoints'
save_steps: 100

optimizer:
  lr: 0.001
  eps: 0.01
  weight_decay: 0.1