per_gpu_train_batch_size: 32
logging_steps: 10
gradient_accumulation_steps: 10
num_train_epochs: 10
train_batch_size: 32
model_save_name: 'CLGP_V1.pth'
saved_checkpoints: 'Model checkpoints'

optimizer:
  lr: 0.001
  eps: 0.01
  weight_decay: 0.1